name: Update Zhihu Follower Badge

on:
  # schedule:
  #   # 每天 UTC 时间00:00 运行
  #   - cron: '0 0 * * *'
  workflow_dispatch:
    # 手动触发

jobs:
  update-badge:
    runs-on: ubuntu-latest

    steps:
    # 检出仓库代码
    - name: Checkout repository
      uses: actions/checkout@v2

    # 获取知乎的 follower 数量并生成 badge
    - name: Generate Zhihu Follower Badge
      run: python generate_badge.py
      
    # 将变更提交到仓库
    - name: Commit and push if changed
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add -A
        git commit -m "Update Zhihu Follower Badge" -a || exit 0 # 如果没有变更则退出
        git push
